/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".btn.btn-default[_ngcontent-%COMP%]{\r\n\r\n    background-color: gray;\r\n    color: white;\r\n    width: 50px;\r\n    height: 40px;\r\n\r\n    }\r\n\r\n.center[_ngcontent-%COMP%]{\r\n        text-align: center\r\n      }\r\n\r\n.container[_ngcontent-%COMP%]{\r\n\r\n  position:absolute;\r\n  padding-top: 40px;\r\n\r\n}"];
export { styles as styles };
