/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["button[_ngcontent-%COMP%]{\r\n\r\n    background-color: #4CAF50;\r\n      border: none;\r\n      color: white;\r\n      padding: 20px;\r\n      text-align: center;\r\n      text-decoration: none;\r\n      display: inline-block;\r\n      font-size: 16px;\r\n      margin: 4px 2px;\r\n  }\r\n  \r\n  .container[_ngcontent-%COMP%]{\r\n  position:absolute;\r\n  padding-top: 40px;\r\n\r\n  }"];
export { styles as styles };
