/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './msgresetmail.component';
const styles_MsgresetmailComponent:any[] = ([] as any[]);
export const RenderType_MsgresetmailComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MsgresetmailComponent,data:{}});
export function View_MsgresetmailComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    \n            '])),(_l()(),
      i0.ɵeld(1,0,(null as any),(null as any),7,'div',[['class','col-md-5 col-md-offset-2']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n             '])),(_l()(),i0.ɵeld(3,0,(null as any),
          (null as any),1,'h2',[['class','text-success bg-dark']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['Sua senha foi resetada!'])),(_l()(),i0.ɵted(-1,(null as any),['\n             '])),
      (_l()(),i0.ɵeld(6,0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
          (null as any),['Um email foi enviado para sua caixa de mensagens com sua nova senha.\n            '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n             '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(null as any),(null as any));
}
export function View_MsgresetmailComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-msgresetmail',
      ([] as any[]),(null as any),(null as any),(null as any),View_MsgresetmailComponent_0,
      RenderType_MsgresetmailComponent)),i0.ɵdid(1,49152,(null as any),0,i1.MsgresetmailComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const MsgresetmailComponentNgFactory:i0.ComponentFactory<i1.MsgresetmailComponent> = i0.ɵccf('app-msgresetmail',
    i1.MsgresetmailComponent,View_MsgresetmailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWxleGEvRGVza3RvcC9ub3ZvL2NhcnJpbmhvL2Fzc2V0cy9hcHAvc3VjY2Vzcy9tc2dyZXNldG1haWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2FsZXhhL0Rlc2t0b3Avbm92by9jYXJyaW5oby9hc3NldHMvYXBwL3N1Y2Nlc3MvbXNncmVzZXRtYWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2FsZXhhL0Rlc2t0b3Avbm92by9jYXJyaW5oby9hc3NldHMvYXBwL3N1Y2Nlc3MvbXNncmVzZXRtYWlsLmNvbXBvbmVudC50cy5Nc2dyZXNldG1haWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL2FsZXhhL0Rlc2t0b3Avbm92by9jYXJyaW5oby9hc3NldHMvYXBwL3N1Y2Nlc3MvbXNncmVzZXRtYWlsLmNvbXBvbmVudC50cy5Nc2dyZXNldG1haWxDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICBcbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtNSBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgICAgICA8aDIgY2xhc3M9XCJ0ZXh0LXN1Y2Nlc3MgYmctZGFya1wiPlN1YSBzZW5oYSBmb2kgcmVzZXRhZGEhPC9oMj5cbiAgICAgICAgICAgICA8aDM+VW0gZW1haWwgZm9pIGVudmlhZG8gcGFyYSBzdWEgY2FpeGEgZGUgbWVuc2FnZW5zIGNvbSBzdWEgbm92YSBzZW5oYS5cbiAgICAgICAgICAgIDwvaDM+XG4gICAgICAgICAgICAgPC9kaXY+XG4gICAgIiwiPGFwcC1tc2dyZXNldG1haWw+PC9hcHAtbXNncmVzZXRtYWlsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDREQUVZO2FBQUE7VUFBQTtNQUFzQyx1REFDckM7VUFBQTtVQUFBLDRDQUFpQztVQUFBLDhCQUE0QjtNQUM3RDtVQUFBLDBEQUFJO1VBQUE7TUFDQSx1REFDRTtVQUFBOzs7b0JDTm5CO01BQUE7c0NBQUEsVUFBQTtNQUFBOzs7In0=
