/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './success.component';
const styles_SuccessComponent:any[] = ([] as any[]);
export const RenderType_SuccessComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_SuccessComponent,data:{}});
export function View_SuccessComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    \n            '])),(_l()(),
      i0.ɵeld(1,0,(null as any),(null as any),7,'div',[['class','col-md-5 col-md-offset-2']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n             '])),(_l()(),i0.ɵeld(3,0,(null as any),
          (null as any),1,'h2',[['class','text-success bg-dark']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['Você foi cadastrado com sucesso!'])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n             '])),(_l()(),i0.ɵeld(6,0,(null as any),(null as any),1,
          'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted(-1,(null as any),['Seus dados serão verificados e se tudo estiver correto,\n                 você receberá um email de confirmação do cadastro.\n            '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n             '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(null as any),(null as any));
}
export function View_SuccessComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-success',
      ([] as any[]),(null as any),(null as any),(null as any),View_SuccessComponent_0,
      RenderType_SuccessComponent)),i0.ɵdid(1,49152,(null as any),0,i1.SuccessComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const SuccessComponentNgFactory:i0.ComponentFactory<i1.SuccessComponent> = i0.ɵccf('app-success',
    i1.SuccessComponent,View_SuccessComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWxleGEvRGVza3RvcC9ub3ZvL2NhcnJpbmhvL2Fzc2V0cy9hcHAvc3VjY2Vzcy9zdWNjZXNzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9hbGV4YS9EZXNrdG9wL25vdm8vY2FycmluaG8vYXNzZXRzL2FwcC9zdWNjZXNzL3N1Y2Nlc3MuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvYWxleGEvRGVza3RvcC9ub3ZvL2NhcnJpbmhvL2Fzc2V0cy9hcHAvc3VjY2Vzcy9zdWNjZXNzLmNvbXBvbmVudC50cy5TdWNjZXNzQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9hbGV4YS9EZXNrdG9wL25vdm8vY2FycmluaG8vYXNzZXRzL2FwcC9zdWNjZXNzL3N1Y2Nlc3MuY29tcG9uZW50LnRzLlN1Y2Nlc3NDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICBcbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtNSBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgICAgICA8aDIgY2xhc3M9XCJ0ZXh0LXN1Y2Nlc3MgYmctZGFya1wiPlZvY8OqIGZvaSBjYWRhc3RyYWRvIGNvbSBzdWNlc3NvITwvaDI+XG4gICAgICAgICAgICAgPGgzPlNldXMgZGFkb3Mgc2Vyw6NvIHZlcmlmaWNhZG9zIGUgc2UgdHVkbyBlc3RpdmVyIGNvcnJldG8sXG4gICAgICAgICAgICAgICAgIHZvY8OqIHJlY2ViZXLDoSB1bSBlbWFpbCBkZSBjb25maXJtYcOnw6NvIGRvIGNhZGFzdHJvLlxuICAgICAgICAgICAgPC9oMz5cbiAgICAgICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLXN1Y2Nlc3M+PC9hcHAtc3VjY2Vzcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSw0REFFWTthQUFBO1VBQUE7TUFBc0MsdURBQ3JDO1VBQUE7VUFBQSw0Q0FBaUM7VUFBQSx1Q0FBcUM7VUFBQSxzQkFDdEU7VUFBQTtVQUFBLGdCQUFJO01BRUEsdURBQ0U7VUFBQTs7O29CQ1BuQjtNQUFBO2lDQUFBLFVBQUE7TUFBQTs7OyJ9
