/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".container[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n    margin:auto;\r\n  }\r\n\r\n  .myleft[_ngcontent-%COMP%]{\r\n    text-align: left; \r\n  }\r\n\r\n \r\n\r\n \r\n \r\n\r\n  #visualizar[_ngcontent-%COMP%]{\r\n    color:white; \r\n    float: left;\r\n  }\r\n\r\n  @media screen and (min-width: 320px) {\r\n    #foto[_ngcontent-%COMP%]{\r\n      width:60%;\r\n      height: 60%;\r\n      \r\n}\r\n\r\n\r\n\r\n  }\r\n\r\n\r\n  @media screen and (min-width: 480px) {\r\n    #foto[_ngcontent-%COMP%]{\r\n      width:70%;\r\n      height: 70%;\r\n      \r\n}\r\n\r\n\r\n\r\n  }\r\n\r\n  @media screen and (min-width: 700px) {\r\n    #foto[_ngcontent-%COMP%]{\r\n      width:80%;\r\n      height:80%;\r\n}\r\n\r\n\r\n  }\r\n\r\n\r\n  @media screen and (min-width: 800px) {\r\n    #foto[_ngcontent-%COMP%]{\r\n      width:100%;\r\n      height:100%;\r\n}\r\n\r\n\r\n  }"];
export { styles as styles };
